### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass-spriting#1]
``` scss
@import "spriting";
// Built on top of the asset api
@import "module-a/assets";
// app assets
@import "assets";

// No magic sprite import.

// support for jpg, gif, and png source files.
// Support for images from different directories
// control the ouput filename (no need for the hash at the end of the filename)
// sprite names are their filenames.
$icon-sprite-map: sprite-map("module-a/sprite-dir/1.jpg",
                             "module-a/sprite-dir/two.png",
                             "my-sprite-dir/**/*",
                             $name: "icons",
                             $layout: sprite-layout(horizontal, (spacing: 5px, alignment: bottom)),
                             $exceptions: (
                               "module-a/sprite-dir/1.jpg": (
                                 spacing: 40px,
                                 identifier: "one"
                               )
                             ));

@debug $icon-sprite-map;
// ( sprite-map: true,
//   name: "icons",
//   sources: (
//     "module-a/sprite-dir/1.jpg",
//     "module-a/sprite-dir/two.png",
//     "my-sprite-dir/**/*"),
//   assets: (
//     "module-a/sprite-dir/1.jpg":
//       (path: "/Users/chris/Projects/mytestproj/node_modules/module-a/images/sprite-dir/1.jpg",
//        identifier: one,
//        position: 0px -10px,
//        width: 40px,
//        height: 40px),
//     "module-a/sprite-dir/two.png":
//       (path: "/Users/chris/Projects/mytestproj/node_modules/module-a/images/sprite-dir/two.png",
//        identifier: two,
//        position: 80px -10px,
//        width: 40px,
//        height: 40px),
//     "my-sprite-dir/foo.png":
//       (path: "/Users/chris/Projects/mytestproj/my-sprite-dir/foo.png",
//        identifier: foo,
//        position: 125px 0px,
//        width: 40px,
//        height: 50px),
//     "my-sprite-dir/bar.gif":
//       (path: "/Users/chris/Projects/mytestproj/my-sprite-dir/bar.gif",
//        identifier: bar,
//        position: 170px -10px,
//        width: 40px,
//        height: 40px),
//     "my-sprite-dir/baz.jpg":
//       (path: "/Users/chris/Projects/mytestproj/my-sprite-dir/baz.jpg",
//        identifier: baz,
//        position: 215px -10px,
//        width: 40px,
//        height: 40px)
//   ),
//   width: 260px,
//   height: 50px,
//   layout: (
//     strategy: horizontal,
//     spacing: 5px,
//     alignment: bottom,
//     exceptions: (
//       "module-a/sprite-dir/1.jpg": (
//         spacing: 40px
//       )
//     )
//   )


@debug sprite-list($icon-sprite-map);
// => "module-a/sprite-dir/1.jpg", "module-a/sprite-dir/two.png",
//    "my-sprite-dir/foo.png", "my-sprite-dir/bar.gif", "my-sprite-dir/baz.jpg"

// Calling the sprite-url function causes the sprite image to be constructed and written to disk.
$url: sprite-url($icon-sprite-map) // => url("/assets/icons.png")
$pos: sprite-position($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 10px -87px
$posx: sprite-position-x($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 10px
$posy: sprite-position-y($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => -87px
$width: sprite-width($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 35px
$height: sprite-height($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 28px
$total-width: sprite-map-width($icon-sprite-map) // => 260px
$total-height: sprite-map-height($icon-sprite-map) // => 50px
// raises an error if called for an image that has no specified identifer and
// the base filename is not a legal css ident.
$id: sprite-identifier($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => one


%icon-bg {
  @include sprite-background($icon-sprite-map); // optional $repeat argument defaults to no-repeat.
  // background: url("/assets/icons.png") no-repeat;
}


.icon-one {
  @extend %icon-bg;
  @include sprite-position($icon-sprite-map, "module-a/sprite-dir/1.jpg");
  // background-position: 10px -87px;
}

@each $icon in sprite-list($icon-sprite-map) {
  .icon-#{sprite-identifier($icon)} {
    @extend %icon-bg;
    @include sprite-position($icon-sprite-map, $icon);
  }
}
```

**Comment by chriseppstein** [comment]
Open questions:
- How does high pixel density work?
- percent-based sizing for more RWD-friendly output.

**Comment by chriseppstein** [comment]
@Jakobo @eoneill @scottdavis Please review!

**Comment by eoneill** [comment]
do we need `sprite-map-(width|height)`, can we just use `sprite-(width|height)` without the second argument?

e.g.

``` scss
$width: sprite-width($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 35px
$height: sprite-height($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 28px
$total-width: sprite-map-width($icon-sprite-map) // => 260px
$total-height: sprite-map-height($icon-sprite-map) // => 50px
```

can be simplified to...

``` scss
$width: sprite-width($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 35px
$height: sprite-height($icon-sprite-map, "module-a/sprite-dir/1.jpg") // => 28px
$total-width: sprite-width($icon-sprite-map) // => 260px
$total-height: sprite-height($icon-sprite-map) // => 50px
```

**Comment by eoneill** [comment]
What does `sprite-layout` return? Does it do some magic that's can't be represented by the map itself?

e.g. instead of...

``` scss
$layout: sprite-layout(horizontal, (spacing: 5px, alignment: bottom)),
```

simplify to...

``` scss
$layout: (horizontal, (spacing: 5px, alignment: bottom)),
```

Also, for the `spacing`, can this support multiple dimensions?

``` scss
spacing: 5px 10px, // 5px top/bottom, 10px right/left
```

You could use the same shorthand rules as margin/padding.

**Comment by chriseppstein** [comment]
> do we need `sprite-map-(width|height)`?

:-1: The terms `sprite` and `sprite-map` are well defined. A sprite is an image that is in a sprite map. So while, the api you suggest is easy enough to implement, it doesn't seem obvious to me given the definitions of those terms.

> What does sprite-layout return? Does it do some magic that's can't be represented by the map itself?

No, I just felt that the code was nicer to read this way. We can certainly move the validation and normalization into the sprite constructor itself. 

> Also, for the spacing, can this support multiple dimensions?

:+1:

**Comment by eoneill** [comment]
> How does high pixel density work?

Started a separate discussion in #2 as this could be a whole other topic.

**Comment by scottdavis** [comment]
I really like the `sprite-layout` idea we had a bunch of feature requests for custom implementations of layouts. It would be killer to have a few built in `horizontal, vertical, smart` and then have the sprite layout maybe expose a factory pattern for laying out your own sprites. It would allow people to build plugins that are just sprite layouts. We could use this same api for building the built in layouts. I think a big issue we ran into with compass sprites was that we keep too much of it under the hood directly with ruby. Now that libsass is a player we can push that up to Sass and not take a performance hit and give people the ability to directly layout the sprites at the canvas level. Manipulation has the potential to really unleash the potential todo cool things like the stuff @hagenburger had laid out in that pdf from ages ago.

We should also support engines so people can make png, gif, jpeg, and svg. The base implementation can use png but this would allow people to make engines that support the other formats.

``` scss
$engine: sprite-gif-engine();
$layout: sprite-layout-create('custom');
$images: sprite-layout-images($layout, sprite-map-images($sprite-map));
$canvas: sprite-layout-canvas($layout);
@each $image in $images {
  $demensions: sprite-image-dimensions($image);
  $height: map_get($dimensions, 'height');
  $canvas: sprite-canvas-add($canvas, sprite-layout-location($image, top: 0px, left: 10px));
 // etc....
}
$map : sprite-map($layout: $layout $engine: $engine,...);
```
