### ISSUE TITLE
Error: error in C function sprite-position: Cannot read property 'coerce' of undefined

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/eyeglass-spriting#10]
This is is happening for me when I try to use `sprite-dimensions` or `sprite-position`, although core spriting functionality (glomming together images) works fine.

``` scss
// Sprites for the foo_bar activity.

@import "spriting"; // eyeglass module
@import "assets";   // eyeglass module

// icon sprites
$foo-bar-sprites: sprite-map(
  'foo-bar-sprites',
  sprite-layout(horizontal, (spacing: 5px, alignment: bottom)),
  'sprites/foo_bar/*'
);


%icon-bg {
  // calling sprite-background generates the sprite map image
  @include sprite-background($foo-bar-sprites);
}

@mixin foo-bar-sprite($which-sprite) {
    @extend %icon-bg;
    @include sprite-position($foo-bar-sprites, $which-sprite);
    // // If all of your sprites are the same size, include sprite-dimensions() in %icon-bg
    @include sprite-dimensions($foo-bar-sprites, $which-sprite);
}
```
