### ISSUE TITLE
[proposal] Support image variants (re: How does high pixel density work?)

### ISSUE THREAD

**Issue by eoneill** [sass-eyeglass/eyeglass-spriting#2]
> How does high pixel density work?

Instead of building a solution to specifically solve the high pixel density case, consider the following proposal that would support any type of "variant".

This assumes the API proposed per #1

Consider the following directory of images.

```
sprites/
  example.jpg
  example@2x.jpg
  example@fr_FR.jpg
  example@fr_FR@2x.jpg
  example@guest.jpg
  example@RTL.jpg
```

``` scss
// create a sprite map
$sprite-map: sprite-map("sprites/example.jpg", ...);
```
- Maybe this is `"sprites/example*.jpg"` or `"sprites/example.jpg", "sprites/example@*.jpg"`?
- Maybe `sprite-map()` / `$exceptions` takes a delimiter (e.g. `$variant-delimiter: '@'`)

``` scss
@debug $sprite-map;
// ( sprite-map: true,
// ...
//   sources: (
//     "sprites/example.jpg"),
//   assets: (
//     "sprites/example.jpg":
//       (path: ".../sprites/example.jpg",
//        identifier: example,
//        position: 0px -10px,
//        width: 40px,
//        height: 40px,
//        variants: (
//          "sprites/example@2x.jpg": (
//            path: ".../sprites/example@2x.jpg",
//            identifier: example,
//            position: ...,
//            width: 80px,
//            height: 80px,
//            variant: (2x)),
//          "sprites/example@fr_FR.jpg": (
//            path: ".../sprites/example@fr_FR.jpg",
//            identifier: example,
//            position: ...,
//            width: 40px,
//            height: 40px,
//            variant: (fr_FR)),
//          "sprites/example@fr_FR@2x.jpg": (
//            path: ".../sprites/example@fr_FR@2x.jpg",
//            identifier: example,
//            position: ...,
//            width: 80px,
//            height: 80px,
//            variant: (fr_FR, 2x)),
//          "sprites/example@guest.jpg": (
//            path: ".../sprites/example@guest.jpg",
//            identifier: example,
//            position: ...,
//            width: 40px,
//            height: 40px,
//            variant: (guest)),
//          "sprites/example@RTL.jpg": (
//            path: ".../sprites/example@RTL.jpg",
//            identifier: example,
//            position: ...,
//            width: 40px,
//            height: 40px,
//            variant: (RTL))
//         )),
//     ...
//   ),
//   ...
```

Then the integration looks something like...

``` scss
.example {
  $sprite: "sprites/example.jpg"
  background: sprite-background($sprite-map, $sprite);

  @media ... {
    background: sprite-background($sprite-map, $sprite, $variant: 2x);
  }

  &:lang(fr) {
    background: sprite-background($sprite-map, $sprite, $variant: fr_FR);

    @media ... {
      background: sprite-background($sprite-map, $sprite, $variant: 2x fr_FR);
    }
  }

  .guest & {
    background: sprite-background($sprite-map, $sprite, $variant: guest);
  }

  &[dir=rtl] {
    background: sprite-background($sprite-map, $sprite, $variant: RTL);
  }
}
```

This would allow you to support any type of image variant with a common convention. It also allows the integration to figure out how they want to support changing variants.

For example, you might not always want to use a `@media` query to define high-res images. You might do something like `<body class="hidef">`, which would allow you to check connection speed etc and not just rely on the pixel density of the device.
